postgresql:
  auth:
    username: fider
    password: s0m3g00dp4ssw0rd
    database: fider
app:
  image:
    repository: getfider/fider
#    tag: stable
    tag: SHA_e0e7dcd3cc4b81107e0d1cdf14e1a0ead35a11b1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: feedback.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
  email:
    noreply: noreply@yourdomain.com
    smtp:
      host: mailhog.example.com
      port: 587
      username: user@yourdomain.com
      password: s0m3p4ssw0rd
      starttls: 'false'
  jwt_secret: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE
