apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          env:
            - name: BASE_URL
              value: https://{{ index .Values.app.ingress.hosts 0 "host" }}
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable
            - name: JWT_SECRET
              value: {{ .Values.app.jwt_secret }}
            - name: EMAIL_NOREPLY
              value: {{ .Values.app.email.noreply | quote }}
            - name: EMAIL_SMTP_HOST
              value: {{ .Values.app.email.smtp.host | quote }}
            - name: EMAIL_SMTP_PORT
              value: {{ .Values.app.email.smtp.port | quote }}
            - name: EMAIL_SMTP_USERNAME
              value: {{ .Values.app.email.smtp.username | quote }}
            - name: EMAIL_SMTP_PASSWORD
              value: {{ .Values.app.email.smtp.password | quote }}
            - name: EMAIL_SMTP_ENABLE_STARTTLS
              value: {{ .Values.app.email.smtp.starttls | quote }}
          ports:
            - containerPort: 3000
